# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9990ba1143c73fe81535379ec63b8dd63c2af9129d9a04778d58b43c5df3513794e42699125a5782980083170c874d0aa41ac5d28a4ee9dd385e2338ed7a1ed6

test:
  secret_key_base: 4279a86254b3edf517179555135986d8f8bf04530bec076af9dae9f7621186060e34219ca53e89a9da2b0aff5f9d19498653e6a3c10599782b81e86f04106945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
